---

- name: Check if Gnome Shell extension is already installed - {{ gnome_extension_info.name }}
  stat:
    path: "{{ ansible_user_dir }}/.local/share/gnome-shell/extensions/{{ gnome_extension_info.uuid }}/metadata.json"
  register: r_gnome_extensions_check_existing

- name: Install Gnome Shell extension - {{ gnome_extension_info.name }}
  ansible.builtin.command: gext install {{ gnome_extension_info.uuid }}
  changed_when: false
  when: not r_gnome_extensions_check_existing.stat.exists

- name: Enable Gnome Shell extension - {{ gnome_extension_info.name }}
  command: gext enable {{ gnome_extension_info.uuid }}
